field: 46b664b4-dbfb-4ca1-a9bb-5ceb8ea79dc6
fieldLayouts:
  33b72364-743c-4142-a84b-9c2d550051d4:
    tabs:
      -
        fields:
          93032bdc-2798-485e-afe5-b3ff6b0ca12c:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  93032bdc-2798-485e-afe5-b3ff6b0ca12c:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f8177c7c-c742-4f87-a809-d650f87e223a'
      defaultUploadLocationSubpath: '@web/assets/blog'
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f8177c7c-c742-4f87-a809-d650f87e223a'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
