field: 46b664b4-dbfb-4ca1-a9bb-5ceb8ea79dc6
fieldLayouts:
  38f424cd-fa63-4baa-9389-ec483efd2882:
    tabs:
      -
        fields:
          9eefdba2-29ae-4994-b996-82574f444ff8:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  9eefdba2-29ae-4994-b996-82574f444ff8:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
