contentColumnType: string
fieldGroup: 22440fad-f451-40df-add8-3af7859e9ed1
handle: aboutImage
instructions: ''
name: 'About image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:36df96a5-fa33-44d7-aaff-023dc84825ca'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:36df96a5-fa33-44d7-aaff-023dc84825ca'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
