contentColumnType: string(244)
fieldGroup: 9b1c99fc-8ca5-4b7d-a6d7-4fa11f4af2ea
handle: blogPostTitle
instructions: 'The blog post title that is not related to the blog post url.'
name: 'Blog Post Title'
searchable: true
settings:
  byteLimit: null
  charLimit: 61
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Lorem ipsum dolor sit amet, consectetur adipiscing ut aliqua.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
