contentColumnType: text
fieldGroup: a72d6e86-5032-4e75-92e8-45e8f585fc0f
handle: brokerTestimonialClientName
instructions: 'The clients name who gave the testimonial'
name: 'Broker Testimonial Client Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Clients Name'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
