contentColumnType: text
fieldGroup: a72d6e86-5032-4e75-92e8-45e8f585fc0f
handle: brokerTestimonialClientCompany
instructions: 'The company the client works for.'
name: 'Broker Testimonial Client Company'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Client Company'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
