contentColumnType: string(255)
fieldGroup: 5bafdda4-3db7-49aa-8a28-f41816993acd
handle: facebookUrl
instructions: ''
name: 'Facebook url'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
