contentColumnType: string
fieldGroup: 51411613-bd67-417e-8a4d-14de88c84b3f
handle: featuredImage
instructions: ''
name: 'Featured image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:f8177c7c-c742-4f87-a809-d650f87e223a'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:f8177c7c-c742-4f87-a809-d650f87e223a'
  singleUploadLocationSubpath: '@web/assets/blog'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
