contentColumnType: string(400)
fieldGroup: 75f34ae8-1828-48c5-adc4-1c7bee461065
handle: headerText
instructions: 'Main heading text for landing page'
name: 'Header text'
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'The seamless solution for businesses with annual insurance to preserve  cash flow.'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
