contentColumnType: text
fieldGroup: 75f34ae8-1828-48c5-adc4-1c7bee461065
handle: tagline
instructions: ''
name: Tagline
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
