contentColumnType: text
fieldGroup: 1ed2b35c-7eee-4016-bd2a-4eb363ede170
handle: teamMemberName
instructions: 'Team Member''s Name'
name: Name
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
