contentColumnType: integer(10)
fieldGroup: 1ed2b35c-7eee-4016-bd2a-4eb363ede170
handle: teamMemberContactNumber
instructions: 'Team member''s contact number'
name: 'Team Member Contact Number'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: '+27'
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
