contentColumnType: text
fieldGroup: 1ed2b35c-7eee-4016-bd2a-4eb363ede170
handle: valueTestimonial
instructions: 'The set value for this team member.'
name: 'Their Value'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
