enableVersioning: true
handle: homePage
name: 'Home Page'
propagationMethod: all
siteSettings:
  41905891-4bbc-4780-afc6-911415166f01:
    enabledByDefault: true
    hasUrls: true
    template: _fulcrum-premium-finance/_singles/_homepage
    uriFormat: __home__
type: single
