enableVersioning: false
handle: insuredLandingPage
name: 'Insured Landing Page'
propagationMethod: all
siteSettings:
  47e975c8-dd55-4c5c-bb74-fe022e68f184:
    enabledByDefault: true
    hasUrls: true
    template: _fulcrum-premium-finance/_singles/_landingpage
    uriFormat: 'fulcrumpremiumfinance-{slug}'
type: single
