enableVersioning: true
handle: singles
name: Singles
propagationMethod: all
siteSettings:
  47e975c8-dd55-4c5c-bb74-fe022e68f184:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
type: single
