enableVersioning: true
handle: whatWeOffer
name: 'What we offer'
propagationMethod: all
siteSettings:
  41905891-4bbc-4780-afc6-911415166f01:
    enabledByDefault: true
    hasUrls: true
    template: _fulcrum-premium-finance/_singles/_what-we-offer
    uriFormat: what-we-offer
type: single
